---
# Copyright 2025, Cleura AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openstack_test_service_groups_length: 3
openstack_test_service_groups:
  - cinder_api
  - galera_all
  - glance_api
  - keystone_all
  - neutron_server
  - nova_api_os_compute
  - placement_all
  - rabbitmq_all

openstack_test_mutualy_exclusive_groups:
  - ['nova_api_os_compute', 'nova_compute']
  - ['neutron_server', 'neutron_ovn_northd']
  - ['neutron_server', 'neutron_ovn_controller']
  - ['neutron_ovn_gateway', 'nova_compute']

openstack_test_collocated_groups:
  - ['nova_compute', 'neutron_ovn_controller']
