---
# Copyright 2017, Logan Vig <logan2211@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Configure keystone for radosgw
  hosts: "{{ openstack_service_setup_host | default('localhost') }}"
  user: root
  tags:
    - ceph-rgw
    - ceph-rgw-setup
    - rgw-service-add
  tasks:

    - name: Setup installation variables
      ansible.builtin.import_role:
        name: openstack.osa.install_defaults
        defaults_from: "{{ install_method | default('source') }}"
      tags:
        - always

    - name: Create user/service in keystone
      ansible.builtin.import_role:
        name: openstack.osa.service_setup
      vars:
        _service_adminuri_insecure: "{{ keystone_service_adminuri_insecure }}"
        _service_setup_host: "{{ inventory_hostname }}"
        _service_setup_host_python_interpreter: >-
          {{
            openstack_service_setup_host_python_interpreter |
              default((openstack_service_setup_host |
                default('localhost') == 'localhost') | ternary(ansible_playbook_python, ansible_facts['python']['executable']))
          }}
        _service_project_name: "{{ radosgw_admin_tenant }}"
        _service_region: "{{ radosgw_service_region }}"
        _service_users:
          - name: "{{ radosgw_admin_user }}"
            password: "{{ radosgw_admin_password }}"
            role: "{{ radosgw_role_name | default('admin') }}"
          - role:
              - name: swiftoperator
                state: present
        _service_catalog:
          - name: "{{ radosgw_service_name }}"
            type: "{{ radosgw_service_type }}"
            description: "{{ radosgw_service_description }}"
        _service_endpoints:
          - interface: "public"
            url: "{{ radosgw_service_publicurl }}"
            service: "{{ radosgw_service_name }}"
          - interface: "internal"
            url: "{{ radosgw_service_internalurl }}"
            service: "{{ radosgw_service_name }}"
          - interface: "admin"
            url: "{{ radosgw_service_adminurl }}"
            service: "{{ radosgw_service_name }}"
      tags:
        - common-service
