---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE(mhayden): CentOS always has python (because of yum), but it's possible
# that Ubuntu nodes may not have python by default. Ansible doesn't work very
# well if Python isn't installed.
#
# Also, we can't use a 'when' to check for the ansible_facts['pkg_mgr'] here because
# we haven't gathered facts yet.
- name: Install Ansible prerequisites
  hosts: "{{ openstack_host_group|default('hosts') }}"
  gather_facts: false
  user: root
  pre_tasks:
    - name: Ensure python is installed
      register: result
      ansible.builtin.raw: |
        if which apt-get >/dev/null && ! which python >/dev/null ; then
          if ! which python3 >/dev/null ; then
            apt-get -y install python3
          fi
          update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          exit 2
        else
          exit 0
        fi
      changed_when: "result.rc == 2"
      failed_when: "result.rc not in [0, 2]"

- name: Gather host facts
  hosts: "{{ openstack_host_group | default('hosts') }}"
  gather_facts: "{{ osa_gather_facts | default(true) }}"
  module_defaults:
    ansible.builtin.setup:
      gather_subset: "{{ osa_gather_subset | default(lookup('ansible.builtin.env', 'ANSIBLE_GATHER_SUBSET', default='!all,min')) }}"
  tags:
    - always

- name: Basic host setup
  hosts: "{{ openstack_host_group|default('hosts') }}"
  gather_facts: false
  user: root
  pre_tasks:
    - name: Setup installation variables
      ansible.builtin.include_role:
        name: openstack.osa.install_defaults
        defaults_from: "{{ install_method }}"
        public: true

    - name: Check for a supported Operating System
      ansible.builtin.include_role:
        name: openstack.osa.platform_check
  roles:
    - role: "openstack_hosts"
  post_tasks:
    - name: Ensure deploy host SSH connection is reset
      ansible.builtin.meta: reset_connection
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - openstack-hosts
