---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather repo facts
  hosts: repo_all
  gather_facts: "{{ osa_gather_facts | default(true) }}"
  module_defaults:
    ansible.builtin.setup:
      gather_subset: "{{ osa_gather_subset | default(lookup('ansible.builtin.env', 'ANSIBLE_GATHER_SUBSET', default='!all,min')) }}"
  tags:
    - always

- name: Setup repo servers
  hosts: repo_all
  gather_facts: false
  serial: "{{ repo_serial | default(['1', '100%']) }}"
  user: root
  pre_tasks:
    - name: End playbook
      ansible.builtin.meta: end_play
      when:
        - (install_method | default('source')) != "source"

    - name: Including container-setup role
      ansible.builtin.include_role:
        name: "openstack.osa.{{ container_tech | default('lxc') }}_container_setup"
      vars:
        list_of_bind_mounts: "{{ repo_container_bind_mounts }}"
      when: not is_metal

    - name: Including unbound-clients role
      ansible.builtin.include_role:
        name: openstack.osa.unbound_clients.yml
      when:
        - hostvars['localhost']['resolvconf_enabled'] | bool
  environment: "{{ deployment_environment_variables | default({}) }}"

- name: Setup repo server gluster cluster
  hosts: repo_all
  gather_facts: false
  user: root
  tasks:
    - name: Create gluster cluster
      ansible.builtin.include_role:
        name: openstack.osa.glusterfs
      vars:
        glusterfs_server_group_name: "repo_all"
        glusterfs_server_volume_name: "gfs-repo"
      when:
        - openstack_repo_server_enable_glusterfs | default(False)
  environment: "{{ deployment_environment_variables | default({}) }}"

- name: Configure haproxy services
  ansible.builtin.import_playbook: openstack.osa.haproxy_service_config
  vars:
    service_group: repo_all
    service_variable: "repo_haproxy_services"
  when: groups[service_group] | length > 0
  tags:
    - haproxy-service-config

- name: Setup repo servers
  hosts: repo_all
  gather_facts: false
  serial: "{{ repo_serial | default(['1', '100%']) }}"
  user: root
  pre_tasks:
    - name: Setup installation variables
      ansible.builtin.include_role:
        name: openstack.osa.install_defaults
        defaults_from: "{{ install_method }}"
        public: true
  roles:
    - role: "repo_server"
  environment: "{{ deployment_environment_variables | default({}) }}"
  tags:
    - repo-server
