---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "integrated-${MOLECULE_SCENARIO_NAME}"
    image: "${DOCKER_REGISTRY:-quay.io/gotmax23}/${DOCKER_IMAGE_TAG:-debian-systemd:bookworm}"
    command: ${DOCKER_COMMAND:-""}
    pre_build_image: true
    privileged: true
    systemd: true
    groups:
      - deploy_host

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      inject_facts_as_vars: false
  inventory:
    links:
      group_vars: ./group_vars/
  playbooks:
    prepare: prepare.yml
    converge: ../../playbooks/healthcheck/user_config.yml

scenario:
  name: user_config
